### ISSUE TITLE
Exportar para Google Calendar

### ISSUE THREAD

**Issue by phsilva** [ramiropolla/capim#2]
Seria interessante se fosse possível gerar uma agenda do Google Calendar (ou um .ical genérico) a partir de um plano escolhido.

Tentarei prototipar isso e mando um pull request em breve.

**Comment by ramiropolla** [comment]
Mas já tem. Vai no menu em baixo do "Sobre" (do lado do identificador), e exporta pra iCalendar. O Google Calendar aceita esse format.

**Comment by phsilva** [comment]
Huhauhau... agora que vi, muito bom!

Tem algum roadmap para o Capim? Se tiver algo que possa ajudar, fala aí.
