### ISSUE TITLE
Criar uma opção para exportar a tabela de horários para excel e/ou derivados

### ISSUE THREAD

**Issue by meyer1994** [ramiropolla/capim#4]
Poderia, ainda, adicionar uma opção para que fossem exportados os nomes inteiros das matérias, não apenas o código delas.
Se não me engano, já existem diversas bibliotecas para isso. No entanto, não entendo muito de python pra ajudar.

**Comment by ramiropolla** [comment]
Opa, eu não to mais desenvolvendo o projeto. Entra em contato no facebook, parece ser o melhor meio de contato no momento. https://www.facebook.com/MatrUFSC
