### ISSUE TITLE
Arquivo iCal exportado inicia eventos em datas erradas

### ISSUE THREAD

**Issue by cauebs** [ramiropolla/capim#5]
Exportei agora o .ics e as datas de início são de 2015, daí todos os eventos ficam fora dos dias da semana corretos.

**Comment by ramiropolla** [comment]
Eu não to mais desenvolvendo o projeto. Entra em contato pelo facebook, parece ser o melhor meio de contato no momento. https://www.facebook.com/MatrUFSC
